# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
source "https://gitlab.linphone.org/BC/public/podspec.git"
source "https://github.com/CocoaPods/Specs.git"


target 'LinphoneSoftphone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LinphoneSoftphone
  pod 'linphone-sdk', '~> 5.0'


end
